export const CHANNEL_MAP = {
  "acc": "acc-network",
  "amc": "amc-eastern-feed",
  "american-heroes": "american-heroes-channel",
  "animal-planet": "animal-planet-us-east",
  "bbc-america": "bbc-america-east",
  "bbc-world": "bbc-news-north-america-hd",
  "bet-east": "bet-eastern-feed",
  "bet-her": "bet-her",
  "big-ten": "big-ten-network",
  "bloomberg": "bloomberg-tv-usa",
  "boomerang": "boomerang",
  "bravo": "bravo-usa-eastern-feed",
  "cspan": "cspan",
  "cartoon-network": "cartoon-network-usa-eastern-feed",
  "cbs-sports-network": "cbs-sports-network-usa",
  "cinemax": "cinemax-eastern-feed",
  "cmt": "cmt-us-eastern-feed",
  "cnbc": "cnbc-usa",
  "cnn": "cnn",
  "comedy-central": "comedy-central-us-eastern-feed",
  "crime-investigation": "crime-investigation-network-usa-hd",
  "destination-america": "destination-america",
  "discovery-channel": "discovery-channel-us-eastern-feed",
  "discovery-family": "discovery-family-channel",
  "discovery-life": "discovery-life-channel",
};
